"""empty message

Revision ID: 3586f61d31b9
Revises: d0e4b3c1c99c
Create Date: 2022-07-17 12:04:11.543405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3586f61d31b9'
down_revision = 'd0e4b3c1c99c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('venue-genres')
    op.drop_table('artists-genres')
    op.drop_column('artists', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.create_table('artists-genres',
    sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('genre_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], name='artists-genres_artist_id_fkey'),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], name='artists-genres_genre_id_fkey'),
    sa.PrimaryKeyConstraint('artist_id', 'genre_id', name='artists-genres_pkey')
    )
    op.create_table('venue-genres',
    sa.Column('genre_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], name='venue-genres_genre_id_fkey'),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], name='venue-genres_venue_id_fkey')
    )
    # ### end Alembic commands ###
