"""empty message

Revision ID: 57caf23ac196
Revises: 5b744ab03e91
Create Date: 2022-07-17 18:44:31.569900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57caf23ac196'
down_revision = '5b744ab03e91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('website_link', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'website_link')
    # ### end Alembic commands ###
