"""empty message

Revision ID: 9db428a271d3
Revises: cc14bf5a0844
Create Date: 2022-07-17 14:17:49.954860

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9db428a271d3'
down_revision = 'cc14bf5a0844'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('showDate', sa.DateTime(), nullable=True))
    op.drop_column('shows', 'showDateTime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('showDateTime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('shows', 'showDate')
    # ### end Alembic commands ###
