"""empty message

Revision ID: 9f7f1d21fd4b
Revises: 3586f61d31b9
Create Date: 2022-07-17 12:39:35.961947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f7f1d21fd4b'
down_revision = '3586f61d31b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('venue_genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venue_genres',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('genre_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], name='venue_genres_genre_id_fkey'),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], name='venue_genres_venue_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='venue_genres_pkey')
    )
    # ### end Alembic commands ###
