"""empty message

Revision ID: cc14bf5a0844
Revises: 9f7f1d21fd4b
Create Date: 2022-07-17 14:12:53.297652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc14bf5a0844'
down_revision = '9f7f1d21fd4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('showDateTime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'showDateTime')
    # ### end Alembic commands ###
